name: PeyangBridge

on:
    push:
        paths: [ "src/**" ]

jobs:
    peyang2develop:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ "ubuntu-latest" ]
                node: [ latest ]
        if: "github.ref == 'refs/heads/peyang'"
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Fetch remote branches
                run: git fetch
            -   name: Use Node.js 15
                uses: actions/setup-node@v1
                with:
                    node-version: 15
            -   name: Checkout branch 'develop'
                uses: actions/checkout@v2
                with:
                    ref: develop
            -   name: Configure git
                run: |
                    git config --global user.email "42040068+peyang-Celeron@users.noreply.github.com"
                    git config --global user.name "peyang-Celeron@BOT"
                    echo '[merge "ours"]' >> .git/config
                    echo '  name = "Keep ours merge"' >> .git/config
                    echo '  driver = true' >> .git/config
            -   name: Apply
                run: git merge --allow-unrelated-histories -Xtheirs "origin/peyang"
            -   name: Stage changed files
                run: git add .
            -   name: npm install, eslint
                run: |
                    npx pnpm i
            -   name: Fix code using ESLint
                run: "npm run fix || true"
            -   name: Commit changes
                uses: EndBug/add-and-commit@v7
                with:
                    author_name: "peyang-Celeron@bot"
                    author_email: "42040068+peyang-Celeron@users.noreply.github.com"
                    branch: develop
                    message: "Fix code-style"
                    signoff: true
            -   name: Print status
                run: git status
            -   name: Push changes
                run: git push
    develop2peyang:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ "ubuntu-latest" ]
                node: [ latest ]
        if: "github.ref == 'refs/heads/develop'"
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Fetch remote branches
                run: git fetch
            -   name: Use Node.js 15
                uses: actions/setup-node@v1
                with:
                    node-version: 15
            -   name: Checkout branch 'peyang'
                uses: actions/checkout@v2
                with:
                    ref: peyang
            -   name: Print directories for debugging
                run: ls
            -   name: Configure
                run: |
                    git config --global user.email "contact@potato1682.ml"
                    git config --global user.name "Potato1682@bot"
                    echo '[merge "ours"]' >> .git/config
                    echo '  name = "Keep ours merge"' >> .git/config
                    echo '  driver = true' >> .git/config
            -   name: Apply
                run: git merge --allow-unrelated-histories -Xtheirs "origin/develop"
            -   name: Stage changed files
                run: git add .
            -   name: Install dependencies using pnpm
                run: npx pnpm i
            -   name: Fix code using ESLint
                run: "npm run fix || true"
            -   name: Commit changes
                uses: EndBug/add-and-commit@v7
                with:
                    author_name: "Potato1682@bot"
                    author_email: "contact@potato1682.ml"
                    branch: peyang
                    message: "Fix code-style"
                    signoff: true
            -   name: Print status
                run: git status
            -   name: Push changes
                run: git push
